# Generated by Django 3.2.5 on 2021-08-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='email',
            field=models.CharField(default='abc@abc.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
